import { primaryColors } from '../source/primary-colors.cjs';

export const brandUtilityColors = {
  // Light Mode Utility Brand Colors
  'utility-brand-50': primaryColors['brand-50'],
  'utility-brand-50-alt': primaryColors['brand-50'],
  'utility-brand-100': primaryColors['brand-100'],
  'utility-brand-100-alt': primaryColors['brand-100'],
  'utility-brand-200': primaryColors['brand-200'],
  'utility-brand-200-alt': primaryColors['brand-200'],
  'utility-brand-300': primaryColors['brand-300'],
  'utility-brand-300-alt': primaryColors['brand-300'],
  'utility-brand-400': primaryColors['brand-400'],
  'utility-brand-400-alt': primaryColors['brand-400'],
  'utility-brand-500': primaryColors['brand-500'],
  'utility-brand-500-alt': primaryColors['brand-500'],
  'utility-brand-600': primaryColors['brand-600'],
  'utility-brand-600-alt': primaryColors['brand-600'],
  'utility-brand-700': primaryColors['brand-700'],
  'utility-brand-700-alt': primaryColors['brand-700'],
  'utility-brand-800': primaryColors['brand-800'],
  'utility-brand-800-alt': primaryColors['brand-800'],
  'utility-brand-900': primaryColors['brand-900'],
  'utility-brand-900-alt': primaryColors['brand-900'],

  // Dark Mode Utility Brand Colors (inverted + alt variants)
  'utility-brand-50-dark': primaryColors['brand-950'],
  'utility-brand-50-alt-dark': primaryColors['gray-900'],
  'utility-brand-100-dark': primaryColors['brand-900'],
  'utility-brand-100-alt-dark': primaryColors['gray-800'],
  'utility-brand-200-dark': primaryColors['brand-800'],
  'utility-brand-200-alt-dark': primaryColors['gray-700'],
  'utility-brand-300-dark': primaryColors['brand-700'],
  'utility-brand-300-alt-dark': primaryColors['gray-700'],
  'utility-brand-400-dark': primaryColors['brand-600'],
  'utility-brand-400-alt-dark': primaryColors['gray-600'],
  'utility-brand-500-dark': primaryColors['brand-500'],
  'utility-brand-500-alt-dark': primaryColors['gray-500'],
  'utility-brand-600-dark': primaryColors['brand-400'],
  'utility-brand-600-alt-dark': primaryColors['gray-400'],
  'utility-brand-700-dark': primaryColors['brand-300'],
  'utility-brand-700-alt-dark': primaryColors['gray-300'],
  'utility-brand-800-dark': primaryColors['brand-200'],
  'utility-brand-800-alt-dark': primaryColors['gray-200'],
  'utility-brand-900-dark': primaryColors['brand-100'],
  'utility-brand-900-alt-dark': primaryColors['gray-100'],
} as const;
