import { primaryColors } from '../source/primary-colors.cjs';

export const stateUtilityColors = {
  'utility-success-50': primaryColors['success-50'],
  'utility-success-100': primaryColors['success-100'],
  'utility-success-200': primaryColors['success-200'],
  'utility-success-300': primaryColors['success-300'],
  'utility-success-400': primaryColors['success-400'],
  'utility-success-500': primaryColors['success-500'],
  'utility-success-600': primaryColors['success-600'],
  'utility-success-700': primaryColors['success-700'],

  'utility-error-50': primaryColors['error-50'],
  'utility-error-100': primaryColors['error-100'],
  'utility-error-200': primaryColors['error-200'],
  'utility-error-300': primaryColors['error-300'],
  'utility-error-400': primaryColors['error-400'],
  'utility-error-500': primaryColors['error-500'],
  'utility-error-600': primaryColors['error-600'],
  'utility-error-700': primaryColors['error-700'],

  'utility-warning-50': primaryColors['warning-50'],
  'utility-warning-100': primaryColors['warning-100'],
  'utility-warning-200': primaryColors['warning-200'],
  'utility-warning-300': primaryColors['warning-300'],
  'utility-warning-400': primaryColors['warning-400'],
  'utility-warning-500': primaryColors['warning-500'],
  'utility-warning-600': primaryColors['warning-600'],
  'utility-warning-700': primaryColors['warning-700'],

  'utility-success-50-dark': primaryColors['success-950'],
  'utility-success-100-dark': primaryColors['success-900'],
  'utility-success-200-dark': primaryColors['success-800'],
  'utility-success-300-dark': primaryColors['success-700'],
  'utility-success-400-dark': primaryColors['success-600'],
  'utility-success-500-dark': primaryColors['success-500'],
  'utility-success-600-dark': primaryColors['success-400'],
  'utility-success-700-dark': primaryColors['success-300'],

  'utility-error-50-dark': primaryColors['error-950'],
  'utility-error-100-dark': primaryColors['error-900'],
  'utility-error-200-dark': primaryColors['error-800'],
  'utility-error-300-dark': primaryColors['error-700'],
  'utility-error-400-dark': primaryColors['error-600'],
  'utility-error-500-dark': primaryColors['error-500'],
  'utility-error-600-dark': primaryColors['error-400'],
  'utility-error-700-dark': primaryColors['error-300'],

  'utility-warning-50-dark': primaryColors['warning-950'], 
  'utility-warning-100-dark': primaryColors['warning-900'],
  'utility-warning-200-dark': primaryColors['warning-800'],
  'utility-warning-300-dark': primaryColors['warning-700'],
  'utility-warning-400-dark': primaryColors['warning-600'],
  'utility-warning-500-dark': primaryColors['warning-500'],
  'utility-warning-600-dark': primaryColors['warning-400'],
  'utility-warning-700-dark': primaryColors['warning-300'],
} as const;
